apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-external
  name: events-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-external
  strategy: {}
  template:
    metadata:
      labels:
        app: events-external
    spec:
      containers:
      - image: shreyaajoshi/capstone_imagef:latest
        name: events-external
        imagePullPolicy: "Always"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}